#Deployment Details

image:
  repository: jenkins/jenkins
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  tag: "lts"

serviceAccount:
  name: jenkins-admin



podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

volumes:
  - name: jenkins-data
    persistentVolumeClaim:
        claimName: jenkins-pv-claim

volumeMounts:
  - name: jenkins-data
    mountPath: /var/jenkins_home


namespace:
  name: "jenkins"