#Deployment Details

image:
  repository: jenkins/jenkins
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  tag: "lts"

serviceAccount:
  name: jenkins-admin



volumes:
  - name: jenkins-data
    persistentVolumeClaim:
        claimName: jenkins-pv-claim

volumeMounts:
  - name: jenkins-data
    mountPath: /var
    subPath: jenkins_home


namespace:
  name: "jenkins"